import { FIELD_TYPES, primaryFieldOf } from '../types/index.js';
import type { EnumField, FieldDefinition, ObjectDefinition } from '../types/index.js';

/**
 * Compile object definitions into object-level TypeScript types
 * (`generated/types.ts`). This is the bridge from contract-level to
 * object-level type safety: consumers `import type { Lead } from './generated/types'`
 * and call `objects<Lead>('lead')`.
 *
 * Pure function, zero dependencies. Field→TS mapping is driven by the
 * `FIELD_TYPES` single source of truth (no hardcoded literals).
 */

/** snake_case → PascalCase (lead → Lead, crm_lead → CrmLead) */
function pascalCase(snake: string): string {
  return snake
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** escape a string for use inside a TS single-quoted string literal */
function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** primary key scalar type of a relation target (fallback: string) */
function relatedPk(target: string, defs: Map<string, ObjectDefinition>): string {
  const pk = primaryFieldOf(defs.get(target));
  if (pk === undefined) return 'string';
  const ts = tsTypeOf(pk, defs);
  return ts === null ? 'string' : ts;
}

function enumType(field: EnumField): string {
  const union = field.options.map((option) => quote(option)).join(' | ');
  return field.multiple === true ? `(${union})[]` : union;
}

/** TS type for a field; null = excluded from the generated interface */
function tsTypeOf(field: FieldDefinition, defs: Map<string, ObjectDefinition>): string | null {
  switch (field.type) {
    case FIELD_TYPES.STRING:
    case FIELD_TYPES.TEXT:
    case FIELD_TYPES.DATETIME:
    case FIELD_TYPES.DATE:
    case FIELD_TYPES.SEQ_NO:
    case FIELD_TYPES.FIRST_NAME:
    case FIELD_TYPES.LAST_NAME:
    case FIELD_TYPES.EMAIL:
    case FIELD_TYPES.PHONE:
    case FIELD_TYPES.IMAGE:
      return 'string';
    case FIELD_TYPES.INTEGER:
    case FIELD_TYPES.NUMBER:
    case FIELD_TYPES.CURRENCY:
      return 'number';
    case FIELD_TYPES.BOOLEAN:
      return 'boolean';
    case FIELD_TYPES.JSON:
      return 'Record<string, unknown>';
    case FIELD_TYPES.ENUM:
      return enumType(field);
    case FIELD_TYPES.RELATION:
    case FIELD_TYPES.PERSON:
    case FIELD_TYPES.DEPARTMENT:
      return relatedPk(field.target, defs);
    case FIELD_TYPES.MULTI_RELATION:
      return `${relatedPk(field.target, defs)}[]`;
    case FIELD_TYPES.DETAILS:
      // child rows are managed via their own object; not embedded in the parent
      return null;
  }
}

/** compile a set of object definitions into TS interface declarations */
export function generateObjectTypes(objects: ObjectDefinition[]): string {
  const defs = new Map(objects.map((obj) => [obj.name, obj]));
  const lines: string[] = ['// Generated by @weave-kit/engine — do not edit.', ''];
  for (const obj of objects) {
    lines.push(`export interface ${pascalCase(obj.name)} {`);
    for (const field of obj.fields) {
      if (field.type === FIELD_TYPES.DETAILS) continue;
      const ts = tsTypeOf(field, defs);
      if (ts === null) continue;
      const optional = ('required' in field && field.required === true) || field.primary === true ? '' : '?';
      lines.push(`  ${field.name}${optional}: ${ts};`);
    }
    lines.push('}', '');
  }
  return lines.join('\n');
}
