import { FIELD_TYPES, primaryFieldOf } from '../types/index.js';
import {
  DEFAULT_FIELD_TYPE_REGISTRY,
  fieldBase,
  type FieldTypeRegistry,
} from '../types/index.js';
import type { EnumDefinition, EnumField, EnumRegistry, FieldDefinition, ObjectDefinition } from '../types/index.js';

/**
 * Compile object definitions into object-level TypeScript types
 * (`generated/types.ts`). This is the bridge from contract-level to
 * object-level type safety: consumers `import type { Lead } from './generated/types'`
 * and call `objects<Lead>('lead')`.
 *
 * Pure function, zero dependencies. Field→TS mapping is driven by the field
 * type's **base** (resolved through the registry), so registered types inherit
 * their base's TS type.
 */

/** snake_case → PascalCase (lead → Lead, crm_lead → CrmLead) */
function pascalCase(snake: string): string {
  return snake
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** escape a string for use inside a TS single-quoted string literal */
function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** primary key scalar type of a relation target (fallback: string) */
function relatedPk(target: string, defs: Map<string, ObjectDefinition>, registry: FieldTypeRegistry): string {
  const pk = primaryFieldOf(defs.get(target));
  if (pk === undefined) return 'string';
  const ts = tsTypeOf(pk, defs, registry);
  return ts === null ? 'string' : ts;
}

function enumType(field: EnumField): string {
  if (!Array.isArray(field.options)) return field.multiple === true ? 'string[]' : 'string';
  const union = field.options.map((option) => quote(option)).join(' | ');
  return field.multiple === true ? `(${union})[]` : union;
}

/** TS type for a field; null = excluded from the generated interface */
function tsTypeOf(
  field: FieldDefinition,
  defs: Map<string, ObjectDefinition>,
  registry: FieldTypeRegistry,
): string | null {
  const base = fieldBase(registry, field.type);
  switch (base) {
    case FIELD_TYPES.STRING:
    case FIELD_TYPES.TEXT:
    case FIELD_TYPES.CHAR:
    case FIELD_TYPES.DATE:
    case FIELD_TYPES.TIME:
    case FIELD_TYPES.TIMETZ:
    case FIELD_TYPES.TIMESTAMP:
    case FIELD_TYPES.TIMESTAMPTZ:
    case FIELD_TYPES.INTERVAL:
    case FIELD_TYPES.UUID:
    case FIELD_TYPES.BIGINT:
    case FIELD_TYPES.SEQ_NO:
      return 'string';
    case FIELD_TYPES.SMALLINT:
    case FIELD_TYPES.INTEGER:
    case FIELD_TYPES.NUMBER:
    case FIELD_TYPES.REAL:
    case FIELD_TYPES.DOUBLE:
    case FIELD_TYPES.CURRENCY:
      return 'number';
    case FIELD_TYPES.BOOLEAN:
      return 'boolean';
    case FIELD_TYPES.JSON:
    case FIELD_TYPES.JSONB:
      return 'Record<string, unknown>';
    case FIELD_TYPES.ENUM:
      return enumType(field as EnumField);
    case FIELD_TYPES.RELATION:
      return relatedPk((field as { target: string }).target, defs, registry);
    case FIELD_TYPES.MULTI_RELATION:
      return `${relatedPk((field as { target: string }).target, defs, registry)}[]`;
    case FIELD_TYPES.DETAILS:
      // child rows are managed via their own object; not embedded in the parent
      return null;
    default:
      return 'unknown';
  }
}

/** shared named-enum types present in the given object set (declared via `enums/`) */
function collectNamedEnums(
  objects: readonly ObjectDefinition[],
  registry: FieldTypeRegistry,
  enums: EnumRegistry | undefined,
): Map<string, EnumDefinition> {
  const out = new Map<string, EnumDefinition>();
  if (enums === undefined) return out;
  for (const object of objects) {
    for (const field of object.fields) {
      if (fieldBase(registry, field.type) !== FIELD_TYPES.ENUM) continue;
      const enumType = (field as { enumType?: string }).enumType;
      if (enumType === undefined) continue;
      const definition = enums.get(enumType);
      if (definition !== undefined) out.set(enumType, definition);
    }
  }
  return out;
}

/** the reference to a shared named-enum TS type, or undefined when the field is not one */
function namedEnumTs(
  field: FieldDefinition,
  registry: FieldTypeRegistry,
  namedEnums: ReadonlyMap<string, EnumDefinition>,
): string | undefined {
  if (fieldBase(registry, field.type) !== FIELD_TYPES.ENUM) return undefined;
  const enumType = (field as { enumType?: string }).enumType;
  if (enumType === undefined || !namedEnums.has(enumType)) return undefined;
  const name = pascalCase(enumType);
  return (field as { multiple?: boolean }).multiple === true ? `${name}[]` : name;
}

/** compile a set of object definitions into TS interface declarations */
export function generateObjectTypes(
  objects: ObjectDefinition[],
  registry: FieldTypeRegistry = DEFAULT_FIELD_TYPE_REGISTRY,
  enums?: EnumRegistry,
): string {
  const defs = new Map(objects.map((obj) => [obj.name, obj]));
  const lines: string[] = ['// Generated by @weave-kit/engine — do not edit.', ''];

  // shared named enums (schema v6): one TS union per declared `enumType`
  const namedEnums = collectNamedEnums(objects, registry, enums);
  if (namedEnums.size > 0) {
    for (const [name, definition] of namedEnums) {
      lines.push(`export type ${pascalCase(name)} = ${definition.values.map(quote).join(' | ')};`);
    }
    lines.push('');
  }

  for (const obj of objects) {
    lines.push(`export interface ${pascalCase(obj.name)} {`);
    for (const field of obj.fields) {
      if (fieldBase(registry, field.type) === FIELD_TYPES.DETAILS) continue;
      const ts = namedEnumTs(field, registry, namedEnums) ?? tsTypeOf(field, defs, registry);
      if (ts === null) continue;
      const optional = ('required' in field && field.required === true) || field.primary === true ? '' : '?';
      lines.push(`  ${field.name}${optional}: ${ts};`);
    }
    lines.push('}', '');
  }
  return lines.join('\n');
}
